# Generated by Django 5.1.1 on 2024-10-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worldcities',
            fields=[
                ('id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('city', models.TextField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('country', models.TextField()),
            ],
            options={
                'db_table': 'worldcities',
                'managed': False,
            },
        ),
    ]
